package:
  name: completebin
  version: 1.1.0.0

source:
  path: /home/datasets/ZOUbohao/Proj3-DeepMetaBin/CompleteBin-v1.0.9.5/CompleteBin/

build: 
  number: 0
  entry_points: 
    - completebin = cli:main

requirements: 
  bulid: 
    - python >=3.9
    - setuptools
  run: 
    - python =3.9.15
    - pandas =1.4.0
    - scikit-learn =0.23.2
    - prodigal =2.6.3
    - hmmer =3.1b2
    - tensorflow >=2.2.0, <=2.12.0
    - galah =0.4.1
    - diamond =2.0.4
    - gsl =2.7.0
    - libopenblas =0.3.25
    - fastANI =1.34
    - pytorch-gpu =2.1.0
    - numpy >=1.17.0, <=1.23.5
    - scipy >=1.8.0
    - tqdm
    - lightgbm
    - skani

test: 
  commands: 
    - completebin -h

about: 
  home: https://github.com/zoubohao/CompleteBin
  license: MIT
  summary: "CompleteBin: Binning with pretrained language model & dynamic contrstive learning"
  description: ""